import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Poppins } from "next/font/google";
import Link from "next/link";

const fontMontserrat = Montserrat({ subsets: ["latin"],
  weight: ['700']
 }
);

const fontPoppins = Poppins({ subsets: ['latin'],
  weight: ['500']
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Header */}
        <header className="w-full h-[100px] bg-[#FFFF] flex items-center">
          <div className="w-full h-[41px] flex flex-row items-center justify-around">

            <div className="w-[185px] h-[41px] gap-[5px] flex flex-row items-center">
              <img className="w-[52px] h-[56px]" src="mainlogo.png" alt="mainlogo"/>
              <div className={fontMontserrat.className}>
               <h1 className="text-[#000000] text-[34px] w-[134px] h-[41px]">Furniro</h1>
              </div>
            </div>

            <div className={fontPoppins.className}>
              <ul className="w-[430px] h-[24px] flex flex-row gap-[48px] justify-center">
                <Link href={`/`}><li className="w-[48px] h-[24px] text-[16px] text-[#000000] cursor-pointer">Home</li></Link>
                <Link href={`/shopSection`}><li className="w-[42px] h-[24px] text-[16px] text-[#000000] cursor-pointer">Shop</li></Link>
                <Link href={`/blogSection`}><li className="w-[36px] h-[24px] text-[16px] text-[#000000] cursor-pointer">Blog</li></Link>
                <Link href={`/contactSection`}><li className="w-[66px] h-[24px] text-[16px] text-[#000000] cursor-pointer">Contact</li></Link>
              </ul>
            </div>

            <div className="flex flex-row gap-[48px] items-center">
              <div className="w-[28px] h-[28px]">
                <img className="w-[23.3px] h-[18.6px] cursor-pointer" src="/navbarlogo/logoOne.png" alt="logoOne" />
              </div>
              <div className="w-[28px] h-[28px]">
                <img className="w-[22.1px] h-[22.1px] cursor-pointer" src="/navbarlogo/logoTwo.png" alt="logoTwo"/>
              </div>
              <div className="w-[28px] h-[28px]">
                <img className="w-[23.3px] h-[20.8px] cursor-pointer" src="/navbarlogo/logoThree.png" alt="logoThree"/>
              </div>
              <div className="w-[28px] h-[28px]">
                <Link href={`/cartSection`}>
                  <img className="w-[24.5px] h-[22.6px] cursor-pointer" src="/navbarlogo/logoFour.png" alt="logoFour"/>
                </Link>
              </div>
            </div>
          </div>
        </header>
        {children}
        <hr className="border bg-[#D9D9D9]"/>
      <div className={fontPoppins.className}>
        <footer className="h-[400px] mt-[32px]">
          <div className="h-[370px] flex flex-col">
            <div className="h-[312px] flex flex-row justify-evenly">
              <div className="flex flex-col justify-evenly">
                <h2 className="w-[85px] h-[36px] font-bold text-[24px] text-[#000000]">Funiro.</h2>
                <p className="w-[285px] h-[72px] font-normal text-[16px] text-[#9F9F9F]">400 University Drive Suite 200 Coral Gables,
                FL 33134 USA</p>
              </div>
              <div className="flex flex-row gap-[64px]">
                <div className="flex flex-col gap-[36px]">        
                  <p className="w-[40px] h-[24px] font-medium text-[16px] text-[#9F9F9F]">Links</p>
                  <div className="w-[66px] h-[233px] flex flex-col gap-[24px]">
                    <p className="w-[48px] h-[24px] font-medium text-[16px]">Home</p>
                    <p className="w-[48px] h-[24px] font-medium text-[16px]">Shop</p>
                    <p className="w-[48px] h-[24px] font-medium text-[16px]">About</p>
                    <p className="w-[72px] h-[24px] font-medium text-[16px]">Contact</p>
                  </div>   
                </div>
                <div className="flex flex-col gap-[36px]">        
                  <p className="w-[40px] h-[24px] font-medium text-[16px] text-[#9F9F9F]">Helps</p>
                  <div className="w-[140px] h-[242px] flex flex-col gap-[24px]">
                    <p className="w-[140px] h-[24px] font-medium text-[16px]">Payment Option</p>
                    <p className="w-[62px] h-[24px] font-medium text-[16px]">Returns</p>
                    <p className="w-[124px] h-[24px] font-medium text-[16px]">Privacy Policies</p>
                  </div>   
                </div>
                <div className="h-[78px] flex flex-col justify-between">
                  <p className="w-[86px] h-[24px] font-medium text-[16px] text-[#9F9F9F]">Newsletter</p>
                  <div className="w-[300px] h-[24px] flex flex-row gap-[24px]">
                    <p className="w-[194px] h-[21px] font-normal text-[14px] text-[#9F9F9F] underline">Enter Your Email Address</p>
                    <p className="w-[75px] h-[21px] font-medium text-[14px] text-[#000000] underline cursor-pointer">SUBSCRIBE</p>
                  </div>
                </div>
              </div>
            </div>
            <hr className="border bg-[#D9D9D9]"/>
            <div className="w-full h-[24px] flex flex-col items-center mt-[32px]">
              <p className="w-[275px] h-[24px] font-normal text-[16px] text-[#000000]">2023 furino. All rights reverved</p>
            </div>
          </div>
        </footer>
      </div>
      </body>
    </html>
  );
}
